import React, { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Loader2, Wand2 } from "lucide-react";
import { toast } from "@/components/ui/use-toast";

const GptStoryPage = () => {
  const [prompt, setPrompt] = useState("");
  const [genre, setGenre] = useState("");
  const [tone, setTone] = useState("");
  const [generating, setGenerating] = useState(false);
  const [generatedStory, setGeneratedStory] = useState("");

  const genres = [
    "Drama",
    "Comedy",
    "Romance",
    "Mystery",
    "Horror",
    "Adventure",
    "Sci-Fi",
    "Fantasy"
  ];

  const tones = [
    "Funny",
    "Serious",
    "Mysterious",
    "Emotional",
    "Inspirational",
    "Dramatic",
    "Casual",
    "Professional"
  ];

  const handleGenerate = async () => {
    if (!prompt || !genre || !tone) {
      toast({
        title: "Error",
        description: "Please fill in all fields",
        variant: "destructive",
      });
      return;
    }

    setGenerating(true);
    try {
      // Simulate API call
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      // Mock story generation
      const mockStory = `Here's your ${tone.toLowerCase()} ${genre.toLowerCase()} story based on: "${prompt}"
      
      [This is a mock story. In production, this would be generated by GPT]
      
      The story unfolds with engaging twists and memorable characters...`;
      
      setGeneratedStory(mockStory);
      
      toast({
        title: "Success",
        description: "Story generated successfully!",
      });
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to generate story",
        variant: "destructive",
      });
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="container py-8">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-3xl font-bold mb-8">GPT Story Generator</h1>
        
        <div className="grid gap-8 md:grid-cols-2">
          <Card>
            <CardHeader>
              <CardTitle>Story Settings</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <label className="text-sm font-medium">Story Prompt</label>
                <Textarea
                  placeholder="Describe your story idea..."
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  className="min-h-[100px]"
                />
              </div>

              <div className="space-y-2">
                <label className="text-sm font-medium">Genre</label>
                <Select value={genre} onValueChange={setGenre}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select genre" />
                  </SelectTrigger>
                  <SelectContent>
                    {genres.map((g) => (
                      <SelectItem key={g} value={g}>
                        {g}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-2">
                <label className="text-sm font-medium">Tone</label>
                <Select value={tone} onValueChange={setTone}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select tone" />
                  </SelectTrigger>
                  <SelectContent>
                    {tones.map((t) => (
                      <SelectItem key={t} value={t}>
                        {t}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <Button
                className="w-full"
                onClick={handleGenerate}
                disabled={generating}
              >
                {generating ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Wand2 className="mr-2 h-4 w-4" />
                    Generate Story
                  </>
                )}
              </Button>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Generated Story</CardTitle>
            </CardHeader>
            <CardContent>
              {generatedStory ? (
                <div className="prose prose-sm">
                  <p className="whitespace-pre-wrap">{generatedStory}</p>
                </div>
              ) : (
                <div className="text-center text-muted-foreground py-8">
                  Your generated story will appear here
                </div>
              )}
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
};

export default GptStoryPage;